name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          set -e

          cd /home/ubuntu || exit 1

          # Clone repo nếu chưa tồn tại
          if [ ! -d "livekit-demo" ]; then
            git clone https://github.com/johnPa02/livekit-demo.git
          fi
          cd livekit-demo

          # Reset về code mới nhất từ remote main
          git fetch origin
          git reset --hard origin/main

          # Ghi file secrets
          echo "${{ secrets.ENV_FILE }}" > docker/.env
          echo '${{ secrets.GCP_CREDENTIALS }}' > docker/gcp-key.json

          # Build & start lại
          docker-compose -f docker/docker-compose.yml up -d --build

          echo "✅ Deployed successfully to EC2"
